site_name: Research Hub
site_subtitle: Research Computing Resources
site_url: https://rcpedia-dev.stanford.edu
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/gsb-logo-color.png
  favicon: assets/images/stanford-favicon.png
  features:
    - content.code.annotate
    - content.code.select
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.tracking
    - content.code.select
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Source Sans Pro
    code: Source Code Pro

plugins:
  - search
  - blog:
      archive: true
      blog_toc: false
      archive_date_format: yyyy
      archive_toc: true
      authors: true
  - tags
 
  # CI=1 mkdocs build
#   - group:
#       enabled: !ENV CI
    #   plugins:
    #     - git-revision-date-localized

  # INSIDERS=1 mkdocs build
  - group:
      enabled: !ENV INSIDERS
      plugins:
        - optimize:
            optimize_png: false

markdown_extensions:
    - attr_list # Enables links open in new tab with {:target="_blank"} syntax 
    - admonition
    - attr_list
    - codehilite
    - toc
    - md_in_html
    - pymdownx.emoji
    - pymdownx.superfences  
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.tabbed:
        alternate_style: true

nav:
  - Status: status.md
  - Getting Started: 
      - Yen Servers: _getting_started/yen-servers.md
      - Access the Yens: _getting_started/how_access_yens.md
      - Jupyter: _getting_started/jupyter.md
      - Modules: _getting_started/modules.md
  - Policies: 
      - Services: _policies/darc.md
      - User Limits: _policies/user_limits.md
      - Collaborators: _policies/collaborators.md
      - Workgroups: _policies/workgroups.md
      - Security: _policies/security.md
      - Human Subjects Research: _policies/humanSubjectsResearch.md
      - Acknowledgements: _policies/acknowledgements.md
      - Leaving GSB: _policies/leavingGSB.md
  - User Guide: 
      - Home: _user_guide/index.md
      - General Practices:
          - Archive: _user_guide/archiving.md
          - File Management: _user_guide/file_management.md
          - Monitor Resource Usage: _user_guide/monitor_usage.md
          - GUI: _user_guide/using_gui.md
          - screen: _user_guide/screen.md
      - Slurm:
          - Slurm: _user_guide/slurm.md
          - Migrating From JupyterHub: _user_guide/migrating_from_jupyter.md
          - Job Arrays: _user_guide/job_arrays.md
          - GPU Slurm Jobs: _user_guide/using_gpu.md
      - Python:
          - Running Python Interactively: _user_guide/python.md
          - Python Virtual Environments: _user_guide/python_envs.md
          - Parallel Processing Python: _user_guide/parallel_processing_python.md
      - R:
          - Running R Interactively: _user_guide/r.md
          - RStudio: _user_guide/rstudio.md
          - Best Practices in R: _user_guide/parallel_processing_r.md
      - Matlab: _user_guide/matlab_interactive.md
      - Julia: _user_guide/julia.md
      - SAS: _user_guide/sas.md          
      - Stata: _user_guide/stata.md          
      - Optimization Software: _user_guide/optimization.md
      - Data:
          - Storage: _user_guide/storage.md
          - Data Transfer: _user_guide/data_transfer.md      
      - Troubleshooting:
          - Why isn't JupyterHub Working?: _user_guide/jupyter_does_not_work.md
          - Man-in-the-Middle Warning: _user_guide/man_in_middle.md
          - Julia on Jupyter: _user_guide/julia_on_jupyter.md
      - Beyond the Yens:
          - Sherlock: _user_guide/sherlock.md
          - Redivis: _user_guide/redivis.md
  - Blog:
      - blog/index.md

extra_css:
  - stylesheets/custom.css

extra_javascript:
#  - js/announcement-banner.js
# - js/announcement-bar.js
  - js/footer.js

extra:
  meta:
    - name: "google-site-verification"
      content: "FtUSXO5iMSrlf4OXVLPXFGPyUKNQuxqSjrY0dlf-ejk"

watch:
  - docs
  - overrides
