site_name: GSB RC Site 2024
site_url: https://rcpedia-dev.stanford.edu
theme:
  name: material
  custom_dir: docs/assets
  features:
    - announce.dismiss
    - header.autohide
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - blogging
  - git-revision-date-localized

markdown_extensions:
  - codehilite
  - toc
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started: 
      - Yen Servers: _getting_started/yen-servers.md
      - Access the Yens: _getting_started/how_access_yens.md 
  - Policies: 
      - Collaborators: _policies/collaborators.md
      - Workgroups: _policies/workgroups.md
      - Services: _policies/services.md
  - User Guide: 
      - Best Practices -- Monitor Resource Usage: _user_guide/best_practices_monitor_usage.md
      - Best Practices -- GUI: _user_guide/best_practices_gui.md
      - Best Practices -- Julia on Jupyter: _user_guide/best_practices_julia_jupyter.md
  - Tech Blog:
      - Optimization Software: _blog/2024-01-26-optimization_software.md 
      - SEC Filings: _blog/2023-05-16-EDGARmirror.md
      - Run on GPU: _blog/2024-03-28-run-gpu.md
      - Edit Files on Command Line: _blog/2023-09-20-edit-files-with-vim.md

extra:
  update_date: 2024-06-27

extra_css:
  - assets/css/index.css
  - assets/css/sh.css
  - assets/css/fonts.css
  - css/custom.css
