site_name: GSB RC Site 2024
site_url: https://rcpedia-dev.stanford.edu
theme:
  name: material
  custom_dir: docs/assets
  features:
    - announce.dismiss
    - header.autohide
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - blogging
  - git-revision-date-localized

markdown_extensions:
  - codehilite
  - toc
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Yen Servers: yen-servers.md
  - Test_page: 
    - Modules: _getting_started/modules.md
    - Parallel Python: _user_guide/parallel_processing_python.md
  - Blog:
      - Optimization Software: _posts/2024-01-26-optimization_software.md 

extra:
  update_date: 2024-06-27

extra_css:
  - assets/css/index.css
  - assets/css/sh.css
  - assets/css/fonts.css
  - css/custom.css
