site_name: Research Computing
site_url: https://rcpedia-dev.stanford.edu
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/gsb-logo-color.webp
  favicon: assets/images/stanford-favicon.png
  features:
    - announce.dismiss
    - header.autohide
    - content.code.annotate
    - content.code.select
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
  # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.tracking
    - content.code.select
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Source Sans Pro
    code: Source Code Pro

plugins:
  - search
  - blog:
      archive: true
      blog_toc: false
      archive_date_format: yyyy
      archive_toc: true
      authors: true
  - tags
 
  # CI=1 mkdocs build
  - group:
      enabled: !ENV CI
      plugins:
        - git-revision-date-localized

  # INSIDERS=1 mkdocs build
  - group:
      enabled: !ENV INSIDERS
      plugins:
        - optimize:
            optimize_png: false

markdown_extensions:
    - attr_list # Enables links open in new tab with {:target="_blank"} syntax 
    - admonition
    - attr_list
    - codehilite
    - toc
    - md_in_html
    - pymdownx.emoji
    - pymdownx.superfences  
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.tabbed:
        alternate_style: true

nav:
  - Home: index.md
  - Getting Started: 
      - Yen Servers: _getting_started/yen-servers.md
      - Access the Yens: _getting_started/how_access_yens.md
      - Jupyter: _getting_started/jupyter.md
      - Modules: _getting_started/modules.md
  - Policies: 
      - User Limits: _policies/user_limits.md
      - Services: _policies/services.md
      - Collaborators: _policies/collaborators.md
      - Workgroups: _policies/workgroups.md
      - Security: _policies/security.md
      - Human Subjects Research: _policies/humanSubjectsResearch.md
      - Acknowledgements: _policies/acknowledgements.md
      - Leaving GSB: _policies/leavingGSB.md
  - User Guide: 
      - General Practices:
          - Archive: _user_guide/best_practices_archive.md
          - File Management: _user_guide/best_practices_file_management.md
          - Monitor Resource Usage: _user_guide/best_practices_monitor_usage.md
          - GUI: _user_guide/best_practices_gui.md
          - screen: _user_guide/best_practices_screen.md
      - Slurm:
          - Slurm: _user_guide/slurm.md
          - Migrating From JupyterHub: _user_guide/best_practices_migrating_from_jupyter.md
          - Job Arrays: _user_guide/job_arrays.md
          - GPU Slurm Jobs: _user_guide/best_practices_gpu.md
      - Python:
          - Python Virtual Environments: _user_guide/best_practices_python_env.md
          - Parallel Processing Python: _user_guide/best_practices_parallel_processing_python.md
      - R:
          - Best Practices in R: _user_guide/best_practices_r.md
      - Matlab:
          - Matlab Slurm Jobs:  _user_guide/best_practices_matlab_slurm_job.md
      - Julia: _user_guide/julia.md
      - SAS: _user_guide/sas.md          
      - Optimization Software: _user_guide/best_practices_optimization.md
      - Data:
          - Storage: _user_guide/storage.md
          - Data Transfer: _user_guide/data_transfer.md      
      - Troubleshooting:
          - Why isn't JupyterHub Working?: _user_guide/best_practices_jupyter_does_not_work.md
          - Man-in-the-Middle Warning: _user_guide/man_in_middle.md
          - Julia on Jupyter: _user_guide/best_practices_julia_jupyter.md
      - Beyond the Yens:
          - Sherlock: _user_guide/sherlock.md
  - Blog:
      - blog/index.md

extra_css:
  - stylesheets/output.css # This is the decanter css tailwind output
  - stylesheets/custom.css # This is custom css
