[build]
  publish = "site"
  command = """
    echo "Creating virtual environment..." &&
    python -m venv .venv &&
    echo "Virtual environment created." &&
    echo "Contents of the current directory:" &&
    ls -al &&
    echo "Activating virtual environment..." &&
    . .venv/bin/activate &&
    echo "Virtual environment activated." &&
    echo "Installing dependencies..." &&
    pip install -r requirements.txt &&
    echo "Dependencies installed." &&
    echo "Building site..." &&
    mkdocs build -d site &&
    echo "Build completed."
  """

[build.environment]
  PIP_NO_CACHE_DIR = "off"
  PYTHON_VERSION = "3.8"