[build]
  publish = "site"
  command = """
    echo "Creating virtual environment..." &&
    python3 -m venv .venv &&
    echo "Activating virtual environment..." &&
    source .venv/bin/activate &&
    echo "Installing dependencies..." &&
    pip install -r requirements.txt &&
    echo "Building site..." &&
    mkdocs build -d site &&
    echo "Build completed."
  """

[build.environment]
  PIP_NO_CACHE_DIR = "off"
  PYTHON_VERSION = "3.8"