[build]
  publish = "site"
  command = """
    echo "Starting build process..." &&
    echo "Installing Poetry..." &&
    pip3 install -q poetry &&
    poetry --version &&
    poetry config virtualenvs.in-project true &&
    echo "Installing dependencies..." &&
    poetry install -v &&
    echo "Building site..." &&
    mkdocs build -d site &&
    echo "Build completed."
  """

[build.environment]
  PYTHON_VERSION = "3.12"