name: Check for Broken Links

on:
  workflow_dispatch:  
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'QA'
  push:
    branches:
      - QA

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write # required for automated issue creation
    steps:
      - name: Check for Broken Links on Deployed Site
        id: lychee
        uses: lycheeverse/lychee-action@v2.3.0
        with:
          args: --verbose --no-progress --max-retries 2 --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" https://rcpedia-dev.stanford.edu

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
