name: Check Markdown links

on:
  workflow_dispatch:  
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
  push:
    branches:
      - main
jobs:
  mkdocs-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: byrnereese/github-action-mkdocs-link-check@1.0
