name: Check for Broken Links

on:
  workflow_dispatch:  
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'QA'
  push:
    branches:
      - QA

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write # Not needed since we removed issue creation
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.3.0
        with:
          fail: false
          args: >
            --verbose 
            --no-progress 
            --timeout 60 
            --max-retries 5 
            --user-agent "Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1"
                  "docs/*.md" 
                  "docs/blog/**/*.md"
                  "docs/_getting_started/**/*.md"
                  "docs/_policies/**/*.md"
                  "docs/_user_guide/**/*.md"

      - name: Show Link Checker Report
        if: always()  # Ensures this runs even if the link check fails
        run: cat ./lychee/out.md || echo "No report generated"
