name: DeployStanford

on:
  push:
    branches:
      - QA
  workflow_dispatch:
    inputs:
        branch:
          description: 'Branch to run the workflow on'
          required: true
          default: 'QA'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Replace placeholders
      env: 
        CPU_NUMBER: ${{ vars.CPU_NUMBER }}
        RAM: ${{ vars.RAM }}
        STORAGE: ${{ vars.STORAGE }}
      run: |
        sed -i "s/CPU_NUMBER_PLACEHOLDER/$CPU_NUMBER/g" mkdocs.yml
        sed -i "s/RAM_PLACEHOLDER/$RAM/g" mkdocs.yml
        sed -i "s/STORAGE_PLACEHOLDER/$STORAGE/g" mkdocs.yml
      
    # ---- Add Debug Step Here ----
    - name: Debug placeholders
      run: |
        echo "mkdocs.yml after placeholder replacement:"
        cat mkdocs.yml
    # -----------------------------     
    - name: Build MkDocs site
      run: mkdocs build --clean

    - name: Upload Site Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: site/
        
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Site Artifacts
      uses: actions/download-artifact@v4
      with:
        name: site

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.MY_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
        echo "${{ secrets.MY_SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to Stanford Hosts
      run: |
        ssh -i ~/.ssh/id_rsa rcpediaq@rcpedia-qa.su.domains "rm -rf /home/rcpediaq/rcpedia-dev.stanford.edu/*"
        scp -i ~/.ssh/id_rsa -r ${{ github.workspace }}/* rcpediaq@rcpedia-qa.su.domains:/home/rcpediaq/rcpedia-dev.stanford.edu
