name: DeployStanford

on:
  workflow_dispatch:  
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'QA'
  push:
    branches:
      - QA
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Replace placeholders in vars.yml
      env: 
        TOTAL_PHYSICAL_CORES: ${{ vars.TOTAL_PHYSICAL_CORES }}
        TOTAL_MEMORY_TB: ${{ vars.TOTAL_MEMORY_TB }}
        TOTAL_GPUS: ${{ vars.TOTAL_GPUS }}
        TOTAL_STORAGE_TB: ${{ vars.TOTAL_STORAGE_TB }}
      run: |
        sed -i "s/TOTAL_PHYSICAL_CORES_PLACEHOLDER/$TOTAL_PHYSICAL_CORES/g" vars.yml
        sed -i "s/TOTAL_MEMORY_TB_PLACEHOLDER/$TOTAL_MEMORY_TB/g" vars.yml
        sed -i "s/TOTAL_GPUS_PLACEHOLDER/$TOTAL_GPUS/g" vars.yml
        sed -i "s/TOTAL_STORAGE_TB_PLACEHOLDER/$TOTAL_STORAGE_TB/g" vars.yml

    - name: Debug placeholder replacement
      run: |
        echo "vars.yml after placeholder replacement:"
        cat vars.yml

    - name: Build MkDocs site
      run: mkdocs build --clean

    - name: Upload Site Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: site/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Site Artifacts
      uses: actions/download-artifact@v4
      with:
        name: site

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.MY_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
        echo "${{ secrets.MY_SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to Stanford Hosts
      run: |
        ssh -i ~/.ssh/id_rsa rcpediaq@rcpedia-qa.su.domains "rm -rf /home/rcpediaq/rcpedia-dev.stanford.edu/*"
        scp -i ~/.ssh/id_rsa -r ${{ github.workspace }}/* rcpediaq@rcpedia-qa.su.domains:/home/rcpediaq/rcpedia-dev.stanford.edu
